### ISSUE TITLE
[Garussian car driverme Recommendation]: <title>

### ISSUE THREAD

**Issue by kingqua503** [nate-games/nate-games.xyz#205]
### Rating

10

### Starred

i allow it

### Game Name

russian  car driver

### URL of the Game

www.y8.com&deviceid=PHYS-SMIC-US-0000-1962&user=007839783&rule=QmxvY2sgfCBTYWZldHkgYW5kIFNlY3VyaXR5IHwgQWxs&ruleid=1b060082-4c25-44c2-b826-28cc1d4ea3a7&path=&method=rule_match

### Game Type

HTML5

### Comment

tfbghngbvhtgfhgvgfytgbhjiuijcghi0dofhgi8hbkcughvhhfhfhkfljiudhiu uh

**Comment by nate-games** [comment]
You do not have the repository starred
